<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Catalyst" Version="26.7.2845" />
        <PackageReference Include="Catalyst.Models.English" Version="1.0.30952" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11"/>
        <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.29.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Localization.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
        </EmbeddedResource>
        <EmbeddedResource Update="Localization.zh.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <DependentUpon>Localization.cs</DependentUpon>
        </EmbeddedResource>
    </ItemGroup>

</Project>
