namespace Centurion.Models.Workflow;

/// <summary>
/// Unified quality report for one subtitle workflow run, written out as .quality.json.
/// Covers input scale, stage coverage, alignment quality, and runtime diagnostics for cross-command comparison and automated consumption.
/// </summary>
public class QualityReport
{
    /// <summary>Run metadata.</summary>
    public QualityMeta Meta { get; set; } = new();

    /// <summary>Scale statistics for input and output.</summary>
    public QualityCounts Counts { get; set; } = new();

    /// <summary>Whether each processing stage completed and its output scale.</summary>
    public QualityCoverage Coverage { get; set; } = new();

    /// <summary>Timeline and alignment quality metrics.</summary>
    public QualityAlignment Alignment { get; set; } = new();

    /// <summary>Line-level timing and readability metrics: CPS, line width, minimum and maximum duration, overlap.</summary>
    public QualityTiming? Timing { get; set; }

    /// <summary>ASR confidence information, when provided by the model.</summary>
    public QualityConfidence? Confidence { get; set; }

    /// <summary>Translation QA metrics: glossary hits, length deviation, back-translation similarity, cache.</summary>
    public QualityTranslation? Translation { get; set; }

    /// <summary>TTS and dubbing alignment and loudness metrics, for the dub command.</summary>
    public QualityTts? Tts { get; set; }

    /// <summary>Line-level issue details; the HTML report can locate each line and these are generated by QualityAssessor.</summary>
    public List<QualityLineIssue> Issues { get; set; } = [];

    /// <summary>Whether all threshold evaluations passed; used by CI and false when --fail-on triggers a failure.</summary>
    public bool Passed { get; set; } = true;

    /// <summary>List of threshold rules that failed, such as "cps>20".</summary>
    public List<string> FailedThresholds { get; set; } = [];

    /// <summary>List of non-fatal warnings.</summary>
    public List<string> Warnings { get; set; } = [];

    /// <summary>List of fatal errors; empty means the run succeeded.</summary>
    public List<string> Errors { get; set; } = [];

    /// <summary>Dub (media localization)-specific metrics; null for non-dub commands.</summary>
    public QualityDub? Dub { get; set; }
}

/// <summary>Run metadata.</summary>
public class QualityMeta
{
    /// <summary>Subcommand name.</summary>
    public string Command { get; set; } = string.Empty;

    /// <summary>Time when the report was generated, ISO 8601.</summary>
    public DateTimeOffset GeneratedAt { get; set; } = DateTimeOffset.Now;

    /// <summary>Input file path.</summary>
    public string InputFile { get; set; } = string.Empty;

    /// <summary>Output file path.</summary>
    public string OutputFile { get; set; } = string.Empty;

    /// <summary>Total elapsed time of this run in seconds.</summary>
    public double ElapsedSeconds { get; set; }
}

/// <summary>Scale statistics for input and output.</summary>
public class QualityCounts
{
    /// <summary>Final number of sentences.</summary>
    public int SentenceCount { get; set; }

    /// <summary>Total number of word-level units, including punctuation and symbols.</summary>
    public int WordCount { get; set; }

    /// <summary>Total number of characters, excluding whitespace.</summary>
    public int CharacterCount { get; set; }

    /// <summary>Number of speakers recognized; 0 or 1 when no diarization was performed.</summary>
    public int SpeakerCount { get; set; }

    /// <summary>Total content duration in seconds: last sentence end minus first sentence start.</summary>
    public double DurationSeconds { get; set; }

    /// <summary>Average speech rate in characters per second.</summary>
    public double CharactersPerSecond { get; set; }
}

/// <summary>Whether each processing stage completed and its output scale.</summary>
public class QualityCoverage
{
    /// <summary>Whether transcription completed.</summary>
    public bool Transcribed { get; set; }

    /// <summary>Whether diarization completed.</summary>
    public bool Diarized { get; set; }

    /// <summary>Whether sentence splitting completed.</summary>
    public bool Split { get; set; }

    /// <summary>Whether forced alignment completed.</summary>
    public bool Aligned { get; set; }

    /// <summary>Whether translation completed.</summary>
    public bool Translated { get; set; }

    /// <summary>Number of transcribed sentences, when present.</summary>
    public int TranscribedSentenceCount { get; set; }

    /// <summary>Number of aligned sentences, when present.</summary>
    public int AlignedSentenceCount { get; set; }

    /// <summary>Number of translated sentences, when present.</summary>
    public int TranslatedSentenceCount { get; set; }
}

/// <summary>Timeline and alignment quality metrics.</summary>
public class QualityAlignment
{
    /// <summary>Mean calibration/mapping drift in milliseconds; null when no calibration data is available.</summary>
    public double? MeanDriftMs { get; set; }

    /// <summary>Maximum drift in milliseconds; null when no calibration data is available.</summary>
    public double? MaxDriftMs { get; set; }

    /// <summary>Text mapping coverage from 0 to 1, for scenarios such as script timing.</summary>
    public double MapperCoverage { get; set; }

    /// <summary>Number of zero-duration sentences where Start == End, an anomaly worth attention.</summary>
    public int ZeroDurationSentenceCount { get; set; }

    /// <summary>Shortest sentence duration in milliseconds.</summary>
    public double MinSentenceDurationMs { get; set; }

    /// <summary>Longest sentence duration in milliseconds.</summary>
    public double MaxSentenceDurationMs { get; set; }
}

/// <summary>Severity of a line-level issue.</summary>
public enum QualityIssueSeverity
{
    /// <summary>Does not affect playback or comprehension, but is worth attention.</summary>
    Warning,

    /// <summary>Clearly affects readability or timeline correctness; CI thresholds usually target this level.</summary>
    Error
}

/// <summary>Type of a line-level issue, one-to-one with the repair engine.</summary>
public enum QualityIssueType
{
    /// <summary>Speech rate exceeds the CPS threshold.</summary>
    CpsTooHigh,

    /// <summary>A single line exceeds the line-width character threshold.</summary>
    LineTooLong,

    /// <summary>Sentence duration is below the minimum duration threshold.</summary>
    TooShort,

    /// <summary>Sentence duration exceeds the maximum duration threshold.</summary>
    TooLong,

    /// <summary>Timeline overlaps with the next sentence.</summary>
    Overlap,

    /// <summary>Zero duration where Start == End.</summary>
    ZeroDuration,

    /// <summary>ASR confidence is below the threshold, when provided by the model.</summary>
    LowConfidence,

    /// <summary>The translation failed to hit the target glossary term.</summary>
    GlossaryMiss,

    /// <summary>The translation length deviates too much from the source.</summary>
    LengthDeviation,

    /// <summary>A negative gap between sentences: the next sentence starts before the previous one ends, i.e. an overlap.</summary>
    NegativeGap
}

/// <summary>A quality issue locatable to a specific subtitle line.</summary>
public class QualityLineIssue
{
    /// <summary>Issue type, as the QualityIssueType name.</summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>Severity: warning / error.</summary>
    public string Severity { get; set; } = QualityIssueSeverity.Warning.ToString();

    /// <summary>Zero-based sentence index; the HTML report line number equals Index + 1.</summary>
    public int SentenceIndex { get; set; }

    /// <summary>Sentence start time in milliseconds.</summary>
    public double StartMs { get; set; }

    /// <summary>Sentence end time in milliseconds.</summary>
    public double EndMs { get; set; }

    /// <summary>The source sentence text, or the translation.</summary>
    public string Text { get; set; } = string.Empty;

    /// <summary>Issue description.</summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>Suggested fix; quality --fix can apply it automatically.</summary>
    public string? Fix { get; set; }

    /// <summary>Quantified value of the issue, such as the actual CPS, actual character count, or overlap in milliseconds.</summary>
    public double? Value { get; set; }

    /// <summary>The threshold for this issue, used for comparison.</summary>
    public double? Limit { get; set; }
}

/// <summary>Timing and readability statistics: CPS, line width, minimum and maximum duration, overlap.</summary>
public class QualityTiming
{
    /// <summary>Average speech rate in characters per second.</summary>
    public double MeanCps { get; set; }

    /// <summary>Maximum per-sentence speech rate in characters per second.</summary>
    public double MaxCps { get; set; }

    /// <summary>Number of sentences exceeding the CPS threshold.</summary>
    public int CpsTooHighCount { get; set; }

    /// <summary>Number of sentences whose single-line character count exceeds the line-width threshold.</summary>
    public int LineTooLongCount { get; set; }

    /// <summary>Number of sentences below the minimum duration threshold.</summary>
    public int TooShortCount { get; set; }

    /// <summary>Number of sentences above the maximum duration threshold.</summary>
    public int TooLongCount { get; set; }

    /// <summary>Number of sentences overlapping with the next one.</summary>
    public int OverlapCount { get; set; }

    /// <summary>Total overlap in seconds.</summary>
    public double TotalOverlapSeconds { get; set; }

    /// <summary>Average gap between sentences in seconds; a negative value indicates overlap.</summary>
    public double MeanGapSeconds { get; set; }
}

/// <summary>ASR confidence information.</summary>
public class QualityConfidence
{
    /// <summary>Average per-sentence confidence from 0 to 1; null when the model did not provide it.</summary>
    public double? MeanConfidence { get; set; }

    /// <summary>Indexes of low-confidence sentences below the threshold.</summary>
    public List<int> LowConfidenceSentenceIndexes { get; set; } = [];
}

/// <summary>Translation QA metrics.</summary>
public class QualityTranslation
{
    /// <summary>Glossary hit rate from 0 to 1: fraction of translated sentences hitting the target term; 1 when no glossary is present.</summary>
    public double GlossaryHitRate { get; set; } = 1;

    /// <summary>Number of sentences that hit a glossary term.</summary>
    public int GlossaryHits { get; set; }

    /// <summary>Number of sentences expected to hit a glossary term.</summary>
    public int GlossaryExpected { get; set; }

    /// <summary>Mean translation-to-source length ratio: &gt;1 means longer, &lt;1 means shorter.</summary>
    public double MeanLengthRatio { get; set; } = 1;

    /// <summary>Mean absolute deviation of the length ratio from 1.0.</summary>
    public double LengthDeviation { get; set; }

    /// <summary>Back-translation similarity from 0 to 1; null when back translation is disabled.</summary>
    public double? BackTranslateSimilarity { get; set; }

    /// <summary>Number of sentences served from the per-sentence cache when --translation-cache is enabled.</summary>
    public int CachedSentenceCount { get; set; }
}

/// <summary>TTS and dubbing alignment and loudness metrics.</summary>
public class QualityTts
{
    /// <summary>Mean error between predicted TTS duration and actual alignment in milliseconds.</summary>
    public double MeanAlignmentErrorMs { get; set; }

    /// <summary>Maximum error between predicted TTS duration and actual alignment in milliseconds.</summary>
    public double MaxAlignmentErrorMs { get; set; }

    /// <summary>Average speech rate in characters per second for TTS synthesis segments.</summary>
    public double MeanSpeechRate { get; set; }

    /// <summary>Average pause between sentences in seconds.</summary>
    public double MeanPauseSeconds { get; set; }

    /// <summary>Maximum pause between sentences in seconds.</summary>
    public double MaxPauseSeconds { get; set; }

    /// <summary>Total negative gap, i.e. overlap, in seconds; 0 when there is no overlap.</summary>
    public double NegativeGapSeconds { get; set; }

    /// <summary>EBU R128 integrated loudness in LUFS; null when probing failed.</summary>
    public double? LoudnessLufs { get; set; }

    /// <summary>Whether ducking was applied; true when accompaniment exists and DubDucking is enabled.</summary>
    public bool DuckingApplied { get; set; }
}

/// <summary>Dub (media localization)-specific quality metrics.</summary>
public class QualityDub
{
    /// <summary>Total number of segments to be dubbed, including chunked sub-segments and skipped items.</summary>
    public int SegmentsTotal { get; set; }

    /// <summary>Number of successfully synthesized segments.</summary>
    public int SegmentsSucceeded { get; set; }

    /// <summary>Number of skipped segments, such as TTS failures.</summary>
    public int SegmentsSkipped { get; set; }

    /// <summary>Translation coverage from 0 to 1: fraction of sentences with translated text.</summary>
    public double TranslationCoverage { get; set; }

    /// <summary>Mean time-alignment deviation in milliseconds: |target duration - aligned duration|.</summary>
    public double MeanAlignmentDeviationMs { get; set; }

    /// <summary>Maximum time-alignment deviation in milliseconds.</summary>
    public double MaxAlignmentDeviationMs { get; set; }

    /// <summary>Minimum final applied tempo ratio via atempo.</summary>
    public double TempoMin { get; set; }

    /// <summary>Maximum final applied tempo ratio via atempo.</summary>
    public double TempoMax { get; set; }

    /// <summary>Average final applied tempo ratio via atempo.</summary>
    public double TempoAverage { get; set; }

    /// <summary>
    /// Clone-consistency heuristic from 0 to 1: rhythmic consistency based on the deviation between synthesized segments and target durations,
    /// not a true voiceprint similarity. When a voiceprint embedding such as TitaNet is available, this field will be replaced by real similarity; it is currently a heuristic proxy.
    /// </summary>
    public double CloneConsistency { get; set; }
}
