<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
        <!-- 允许测试程序集与实现层访问 internal 成员 -->
        <InternalsVisibleTo Include="Centurion.Tests" />
        <InternalsVisibleTo Include="Centurion.Core" />
    </ItemGroup>

</Project>
