<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
        <PackageReference Include="Spectre.Console" Version="0.57.2" />
        <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Centurion.Models\Centurion.Models.csproj" />
      <ProjectReference Include="..\Centurion.Abstractions\Centurion.Abstractions.csproj" />
      <ProjectReference Include="..\Centurion.Core\Centurion.Core.csproj" />
    </ItemGroup>

    <Target Name="MoveSatelliteAssemblies" AfterTargets="AfterBuild" Condition="'$(Configuration)' == 'Debug' Or '$(Configuration)' == 'Release'">
        <ItemGroup>
            <SatelliteAssemblies Include="$(OutputPath)**\*.resources.dll"
                                 Exclude="$(OutputPath)Resources\**;$(OutputPath)win-x64\**" />
            <SatelliteAssembliesToMove Include="@(SatelliteAssemblies)" Condition="Exists('%(FullPath)')" />
        </ItemGroup>
        <Move SourceFiles="@(SatelliteAssembliesToMove)" DestinationFolder="$(OutputPath)Resources\%(RecursiveDir)" />
        <RemoveDir Directories="@(SatelliteAssembliesToMove->'%(RootDir)%(Directory)')" Condition="Exists('%(RootDir)%(Directory)')" />
    </Target>

    <PropertyGroup>
        <ApplicationIcon>app.ico</ApplicationIcon>
    </PropertyGroup>

</Project>
