using System.Text.Json;

namespace Centurion.Abstractions;

/// <summary>
/// Configuration from <c>centurion.config.json</c> with environment variable overrides.
/// Precedence: built-in defaults &lt; <c>centurion.config.json</c> &lt; <c>CENTURION_*</c> environment variables &lt; command-line arguments.
/// </summary>
/// <example>
/// Example configuration file in the current directory:
/// <code>
/// { "profile": "offline", "language": "zh-CN", "outputFormat": "ass" }
/// </code>
/// Environment variables: CENTURION_PROFILE, CENTURION_LANG, CENTURION_GITHUB_PROXY,
/// CENTURION_LOG_LEVEL、CENTURION_JSON、CENTURION_OUTPUT_FORMAT。
/// </example>
public sealed class CenturionConfig
{
    /// <summary>Provider selection profile: offline / fast / quality / cheap.</summary>
    public string? Profile { get; set; }

    /// <summary>Runtime UI language code, such as zh-CN.</summary>
    public string? Language { get; set; }

    /// <summary>GitHub download proxy prefix; null or an empty string disables the proxy.</summary>
    public string? GithubProxy { get; set; }

    /// <summary>Output result summaries as JSON by default.</summary>
    public bool? Json { get; set; }

    /// <summary>Log level: trace / debug / information / warning / error / critical.</summary>
    public string? LogLevel { get; set; }

    /// <summary>Default subtitle output format: ass / srt / txt.</summary>
    public string? OutputFormat { get; set; }

    /// <summary>Recommended command chain generated by the init wizard; display-only and not parsed.</summary>
    public string? Recipe { get; set; }

    /// <summary>Loads configuration from centurion.config.json in the current directory and environment variables.</summary>
    public static CenturionConfig Load(string? configPath = null)
    {
        var config = new CenturionConfig();

        var path = configPath ?? FindConfigFile();
        if (path is not null && File.Exists(path))
        {
            try
            {
                var parsed = JsonSerializer.Deserialize<CenturionConfig>(File.ReadAllText(path),
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                if (parsed is not null)
                    config = parsed;
            }
            catch (JsonException)
            {
                // Silently fall back to defaults; the caller decides whether to report this during CLI startup.
            }
        }

        // Environment variables override the configuration file.
        if (GetEnv("CENTURION_PROFILE") is { } p && p.Length > 0) config.Profile = p;
        if (GetEnv("CENTURION_LANG") is { } l && l.Length > 0) config.Language = l;
        if (GetEnv("CENTURION_GITHUB_PROXY") is { } g) config.GithubProxy = g.Length == 0 ? "" : g;
        if (GetEnv("CENTURION_LOG_LEVEL") is { } ll && ll.Length > 0) config.LogLevel = ll;
        if (GetEnv("CENTURION_JSON") is { } j && bool.TryParse(j, out var bj)) config.Json = bj;
        if (GetEnv("CENTURION_OUTPUT_FORMAT") is { } of && of.Length > 0) config.OutputFormat = of;

        return config;
    }

    /// <summary>Searches for centurion.config.json in the current directory and up to two parent directories.</summary>
    private static string? FindConfigFile()
    {
        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        for (var i = 0; i < 3 && dir is not null; i++, dir = dir.Parent)
        {
            var candidate = Path.Combine(dir.FullName, "centurion.config.json");
            if (File.Exists(candidate))
                return candidate;
        }
        return null;
    }

    private static string? GetEnv(string name)
    {
        try { return Environment.GetEnvironmentVariable(name); }
        catch (System.Security.SecurityException) { return null; }
    }
}
